### ISSUE TITLE
Remapping to MCP remaps access to synthetic methods in bootstrap methods incorrectly

### ISSUE THREAD

**Issue by ShadewEnder** [architectury/architectury-plugin#1]
Ok this is a very complicated issue, but long story short: the Mojmap to MCP remapper remaps methods it should not remap. When remapping to MCP, the remapper might take into account the usage of synthetic `lambda$x$y` methods in bootstrap methods. Here's an example of two bytecode reports of the same class on different loaders, the top one being that of forge and the bottom one being that of fabric:

![image](https://user-images.githubusercontent.com/11669132/102831511-48f09000-43ec-11eb-8b0f-89218bb00bd0.png)

I underlined the error: `lambda$getMenuProvider$0` is not supposed to remap to `func_220270_a`, since it's a private, synthetic member of a class that belongs to the mod. Looking at the code I'm not sure whether the origin of this issue is the Architectury plugin or TinyRemapper, but my first thought is that it is Architectury, because the Mojmap to Yarn remapper uses TinyRemapper too and that one doesn't have the issue.

**Comment by ShadewEnder** [comment]
At last this eventually leads to generated Forge mods not working properly. We got strange crash reports of `IllegalAccessError`s accessing a private method and it was that same method `func_220270_a` - we had to dig deep into the bytecode to reveal the actual remapper issue.

**Comment by shedaniel** [comment]
I will look into this issue, however this seems complicated, and I am focusing into migrating over to forgeloom instead.

**Comment by shedaniel** [comment]
No longer relevant.
