### ISSUE TITLE
Alternative expected package for Impls of @ExpectPlatform methods

### ISSUE THREAD

**Issue by Trikzon** [architectury/architectury-plugin#16]
# Alternative expected package for Impls of @ExpectPlatform methods

## Enhancement Description

Currently, when using `@ExpectPlatform` the implementation should be located as such:
```
com.examplemod.modid.foo.bar.FooBar (contains the @ExpectPlatform annotation)
com.examplemod.modid.foo.bar.fabric.FooBarImpl
com.examplemod.modid.foo.bar.forge.FooBarImpl
```

It would be great if instead, the expected package for Impls is as follows:
```
com.examplemod.modid.foo.bar.FooBar (contains the @ExpectPlatform annotation)
com.examplemod.modid.fabric.foo.bar.FooBarImpl
com.examplemod.modid.forge.foo.bar.FooBarImpl
```

## Implementation Ideas

1. Somehow use the maven_group and archives_base_name (not ideal).
2. Require the "root" package to be initialized `ExpectPlatform.setPackage("com.examplemod.modid");`
3. Add an optional String parameter to the @ExpectPlatform annotation that specifies a package.

**Comment by shedaniel** [comment]
I will allow you to use placeholders, possibly.
