### ISSUE TITLE
1.17 crashes when used with OptiFabric

### ISSUE THREAD

**Issue by quiqueck** [architectury/architectury-plugin#21]
Using 
- OptiFarbic (1.11.1)  
- preview_OptiFine_1.17_HD_U_G9_pre16 
- architectury (2.0.7) 

in MC 1.17 results in a crash

[latest.log](https://github.com/architectury/architectury-plugin/files/6641882/latest.log)

**Comment by shedaniel** [comment]
Report to OptiFabric
