### ISSUE TITLE
Incorrect classpath in eclipse

### ISSUE THREAD

**Issue by warjort** [architectury/architectury-plugin#4]
Using ./gradlew eclipse generates the wrong eclipse classpath for the forge subproject.

The following would be an example of the changes needed to the generated forge/.classpath in architectury itself.

-<classpathentry kind="src" path="/common"/>
+<classpathentry kind="lib" path="/common/build/libs/architectury-1.1.9999-mcp.jar" sourcepath="/common/src/main/java"/>

i.e. the forge project depends on the generated mcp jar rather than the common project directly

I can't see a trivial way to fix it from this page?
https://docs.gradle.org/current/dsl/org.gradle.plugins.ide.eclipse.model.EclipseClasspath.html

**Comment by shedaniel** [comment]
We are not supporting eclipse in the near future, I am adding a wontfix tag.

**Comment by warjort** [comment]
This issue became kind of irrelvant when using the same mappings for fabric and forge.
At least I haven't had a problem with it.

Why is eclipse no longer supported? You know visual studio uses the same code for gradle integration as well?

**Comment by Juuxel** [comment]
Minecraft run configs are created differently on each platform, and Arch Loom needs some extra run config features compared to upstream Loom, which are currently only implemented for IDEA and VS Code run configs. (There might also be something else, but this is one of the main issues.)

**Comment by warjort** [comment]
Ok, thanks for the info. 
I personally don't use the run configs, so I think you could say eclipse only has limited support?

Anyway, I will close this issue.
